
package soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BassServiceImplService", targetNamespace = "http://agwems.kt.com/", wsdlLocation = "http://localhost:30388/agwems?wsdl")
public class BassServiceImplService
    extends Service
{

    private final static URL BASSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException BASSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName BASSSERVICEIMPLSERVICE_QNAME = new QName("http://agwems.kt.com/", "BassServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:30388/agwems?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BASSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        BASSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public BassServiceImplService() {
        super(__getWsdlLocation(), BASSSERVICEIMPLSERVICE_QNAME);
    }

    public BassServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BASSSERVICEIMPLSERVICE_QNAME, features);
    }

    public BassServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, BASSSERVICEIMPLSERVICE_QNAME);
    }

    public BassServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BASSSERVICEIMPLSERVICE_QNAME, features);
    }

    public BassServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BassServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BassServiceInterface
     */
    @WebEndpoint(name = "BassServiceImplPort")
    public BassServiceInterface getBassServiceImplPort() {
        return super.getPort(new QName("http://agwems.kt.com/", "BassServiceImplPort"), BassServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BassServiceInterface
     */
    @WebEndpoint(name = "BassServiceImplPort")
    public BassServiceInterface getBassServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://agwems.kt.com/", "BassServiceImplPort"), BassServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BASSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw BASSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return BASSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
